name: ghpages-updater

on:
  release:
    types:
      - published

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: |
          sudo apt install -y cmake ninja-build clang pandoc
      - name: Get the version
        id: get_version
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build docs
        run: |
          mkdir build
          cd build
          rm -rf CMakeCache.txt && cmake -GNinja -DCMAKE_C_COMPILER=clang -DCMAKE_RC_COMPILER=windres -DCMAKE_C_STANDARD=11 -DCMAKE_C_STANDARD_REQUIRED=ON -DCMAKE_C_EXTENSIONS=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Release .. && ninja -v make_doc
          cd ..
          mv build/bin/PSDToolKitDocs ../docs
          git checkout --orphan gh-pages
          git clean -fdx
          git rm -rf * .github .clang-format .gitattributes .gitignore .gitmodules
          mv ../docs/* ./
          git add .
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m docs
          git push -f origin gh-pages
